export const Types = {
  user: {
    LOGIN_USER_SUCCESS: "LOGIN_USER_SUCCESS",
    LOGIN_USER_FAILED: "LOGIN_USER_FAILED",
    SET_LOGIN_LOADING: "SET_LOGIN_LOADING",
    REMOVE_LOGIN_LOADING: "REMOVE_LOGIN_LOADING",

    UPDATE_LOGIN_DETAILS: "UPDATE_LOGIN_DETAILS",

    GET_USER_DETAILS: "GET_USER_DETAILS",
    UPDATE_USER_DETAILS: "UPDATE_USER_DETAILS",

    SELECT_USER: "SELECT_USER",
    ENROLL_USER_IN_COURSE: "ENROLL_USER_IN_COURSE",
    UNENROLL_USER_IN_COURSE: "UNENROLL_USER_IN_COURSE",

    GET_ALL_USERS: "GET_ALL_USERS",

    NEXT_PAGE_USER: "NEXT_PAGE_USER",
    PREV_PAGE_USER: "PREV_PAGE_USER",

    LOGOUT_USER: "LOGOUT_USER",
  },
  course: {
    COURSE_LOADING: "COURSE_LOADING",
    REMOVE_COURSE_LOADING: "REMOVE_COURSE_LOADING",

    ADD_NEW_COURSE: "ADD_NEW_COURSE",
    CREATE_NEW_VIDEO: "CREATE_NEW_VIDEO",

    GET_ALL_COURSE: "GET_ALL_COURSE",

    GET_COURSE_VIDEOS: "GET_COURSE_VIDEOS",

    DELETE_COURSE: "DELETE_COURSE",
    DELETE_VIDEO: "DELETE_VIEDO",

    COURSE_UPDATE: "COURSE_UPDATE",
  },
  modal: {
    ASK_DELETE_COURSE: "ASK_DELETE_COURSE",
    ASK_DELETE_VIDEO: "ASK_DELETE_VIDEO",

    ADD_NEW_VIDEO: "ADD_NEW_VIDEO",

    ASK_DELETE_VIDEO: "ASK_DELETE_VIDEO",

    ADD_ADMIN_ROLE: "ADD_ADMIN_ROLE",
    REMOVE_ADMIN_ROLE: "REMOVE_ADMIN_ROLE",

    SELECT_USER_MODAL: "SELECT_USER_MODAL",

    // @ ask new changes
    ADD_PRODUCT_MODAL: "ADD_PRODUCT_MODAL",
    DELETE_PRODUCT_MODAL: "DELETE_PRODUCT_MODAL",
  },
  contact: {
    GET_ALL_CONTACTS: "GET_ALL_CONTACTS",

    NEXT_PAGE_CONTACTS: "NEXT_PAGE_CONTACTS",
    PREV_PAGE_CONTACTS: "PREV_PAGE_CONTACTS",

    CONTACT_SET_LOADING: "CONTACT_SET_LOADING",
    CONTACT_REMOVE_LOADING: "CONTACT_REMOVE_LOADING",

    RESET_CONTACT: "RESET_CONTACT",
  },
  payment: {
    GET_ALL_PAYMENT: "GET_ALL_PAYMENT",

    NEXT_PAGE_PAYMENT: "NEXT_PAGE_PAYMENT",
    PREV_PAGE_PAYMENT: "PREV_PAGE_PAYMENT",

    PAYMENT_SET_LOADING: "PAYMENT_SET_LOADING",
    PAYMENT_REMOVE_LOADING: "PAYMENT_REMOVE_LOADING",
  },
  products: {
    GET_ALL_PRODUCTS: "GET_ALL_PRODUCTS",
    ADD_NEW_PRODUCT: "ADD_NEW_PRODUCT",
    GET_PRODUCT_BY_ID: "ADD_NEW_PRODUCT",
    REMOVE_PRODUCT: "ADD_NEW_PRODUCT",

    SET_PRODUCT_LOADING: "SET_PRODUCT_LOADING",
    REMOVE_PRODUCT_LOADING: "REMOVE_PRODUCT_LOADING",
  },
  orders: {
    GET_ALL_ORDERS: "GET_ALL_ORDERS",
    GET_ORDER_BY_USERID: "GET_ORDER_BY_USERID",

    SET_CURRENT_ORDER: "SET_CURRENT_ORDER",
    REMOVE_CURRENT_ORDER: "REMOVE_CURRENT_ORDER",

    UPDATE_CURRENT_ORDER: "UPDATE_CURRENT_ORDER"
  },
  config: {
    TOGGLE_SIDEBAR: "TOGGLE_SIDEBAR",
  }
};
